package net.javierjimenez.Botiga_Escriptori;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import static com.mongodb.client.model.Filters.*;

import org.bson.Document;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class StartController {
	@FXML
	private TextField nomProd;
	@FXML
	private Button buscarNom;
	@FXML
	private TextField portada;
	@FXML
	private TextField juego;
	@FXML
	private TextField escena1;
	@FXML
	private TextField escena2;
	@FXML
	private TextField nombre;
	@FXML
	private TextField genero;
	@FXML
	private TextField distribuidora;
	@FXML
	private TextField plataforma;
	@FXML
	private TextField cantidad;
	@FXML
	private TextField precio;
	@FXML
	private Button nuevo;
	@FXML
	private Button editar;
	@FXML
	private Button anterior;
	@FXML
	private Button siguiente;
	@FXML
	private ComboBox<String> edad = new ComboBox<>();
	@FXML
	private ComboBox<String> activar = new ComboBox<>();
	
	private MongoClient client;
	
	private MongoCollection<Document> col;

	public void initialize(URL arg0, ResourceBundle arg1) {
		
		client = new MongoClient(new MongoClientURI("mongodb://admin000:admin001@ds013212.mlab.com:13212/botiga_daw"));

		MongoDatabase db = client.getDatabase("botiga_daw");

		col = db.getCollection("products");
		
	}
	
	@FXML
	public void buscarNombre(ActionEvent event) {
		
		String nombre = nomProd.getText();
		
		System.out.println(nombre);
		
		Document d = new Document("nom", nombre);
		
		col.insertOne(d);
		
		anterior.setDisable(true);
		siguiente.setDisable(true);
		editar.setDisable(true);
		
	}
	
	@FXML
	public void nuevoProducto(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void productoAnterior(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void siguienteProducto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editar].onAction
	@FXML
	public void editarProducto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#edad].onAction
	@FXML
	public void edadProd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#activar].onAction
	@FXML
	public void selActivar(ActionEvent event) {
		// TODO Autogenerated
	}
}
