package net.javierjimenez.Botiga_Escriptori;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import static com.mongodb.client.model.Filters.eq;

import java.net.URL;
import java.util.ResourceBundle;

import org.bson.Document;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class StartController {
	@FXML
	private TextField nomProd;
	@FXML
	private Button buscarNom;
	@FXML
	private TextField portada;
	@FXML
	private TextField juego;
	@FXML
	private TextField escena1;
	@FXML
	private TextField escena2;
	@FXML
	private TextField nombre;
	@FXML
	private TextField genero;
	@FXML
	private TextField distribuidora;
	@FXML
	private TextField plataforma;
	@FXML
	private TextField cantidad;
	@FXML
	private TextField precio;
	@FXML
	private Button nuevo;
	@FXML
	private Button editar;
	@FXML
	private ComboBox<String> edad = new ComboBox<>();
	@FXML
	private ComboBox<String> activar = new ComboBox<>();
	
	private MongoClient client;
	
	private MongoCollection<Document> col;

	public void initialize(URL arg0, ResourceBundle arg1) {
		
		client = new MongoClient(new MongoClientURI("mongodb://admin000:admin001@ds013212.mlab.com:13212/botiga_daw"));

		MongoDatabase db = client.getDatabase("botiga_daw");

		col = db.getCollection("products");
		
	}
	
	@FXML
	public void buscarNombre(ActionEvent event) {
		
		String nombre = nomProd.getText();
		
		Document doc = col.find(eq("castella", nombre)).first();
		
		if (doc == null) {
			Alert alert = new Alert(AlertType.WARNING);
			alert.setTitle("Problema de Búsqueda");
			alert.setHeaderText("ALERTA: Problema en la búsqueda");
			alert.setContentText("Los datos escritos son erróneos o\nno existe dicho nombre.\nRehaga la búsqueda.");
			alert.showAndWait();
		} else {
			
		}	
	}
	
	@FXML
	public void nuevoProducto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editar].onAction
	@FXML
	public void editarProducto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#edad].onAction
	@FXML
	public void edadProd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#activar].onAction
	@FXML
	public void selActivar(ActionEvent event) {
		// TODO Autogenerated
	}
}
